#version 460

layout (local_size_x = 16, local_size_y = 8, local_size_z = 1) in;

layout (set=0, binding = 0, rgba8ui) uniform writeonly uimage2D outputImageColor;

void main() {

  const ivec2 imageColorDim = imageSize(outputImageColor);
  const vec2 uvcoord = vec2(gl_GlobalInvocationID.xy) / vec2(imageColorDim);

  if (uvcoord.x > 1.0f || uvcoord.y > 1.0f) {
    return;
  }

  imageStore(
    outputImageColor,
    ivec2(gl_GlobalInvocationID.xy),
    uvec4(255, 255, 255, 255)
  );
}
