const vk = @import("vulkan.zig");

pub const VulkanBaseDispatch = vk.BaseWrapper(&.{
  .createInstance,
});

pub const VulkanInstanceDispatch = vk.InstanceWrapper(&.{
  .createDevice,
  .getPhysicalDeviceFeatures2,
  .destroyInstance,
  .destroySurfaceKHR,
  .enumerateDeviceExtensionProperties,
  .enumeratePhysicalDevices,
  .getDeviceProcAddr,
  .getPhysicalDeviceMemoryProperties,
  .getPhysicalDeviceMemoryProperties2,
  .getPhysicalDeviceProperties,
  .getPhysicalDeviceProperties2,
  .getPhysicalDeviceQueueFamilyProperties,
  .getPhysicalDeviceSurfaceCapabilitiesKHR,
  .getPhysicalDeviceSurfaceFormatsKHR,
  .getPhysicalDeviceSurfacePresentModesKHR,
  .getPhysicalDeviceSurfaceSupportKHR,
});

pub const VulkanDeviceDispatch = vk.DeviceWrapper(&.{
  // .acquireNextImageKHR,
  .allocateCommandBuffers,
  .allocateDescriptorSets ,
  .allocateMemory,
  .beginCommandBuffer,
  .bindBufferMemory,
  .cmdBeginRenderPass,
  .cmdBindDescriptorSets ,
  .cmdBindPipeline,
  .cmdBindVertexBuffers,
  // .cmdBuildAccelerationStructuresKHR,
  .cmdCopyBuffer2KHR,
  .cmdCopyImageToBuffer2KHR,
  .cmdDispatch,
  .cmdDraw,
  .cmdEndRenderPass,
  .cmdFillBuffer,
  .cmdPipelineBarrier,
  .cmdSetScissor,
  .cmdSetViewport,
  // .cmdWriteAccelerationStructuresPropertiesKHR,
  // .createAccelerationStructureKHR,
  .createBuffer,
  .createCommandPool,
  .createComputePipelines,
  .createDescriptorPool ,
  .createDescriptorSetLayout ,
  .createFence,
  .createFramebuffer,
  .createGraphicsPipelines,
  .createImageView,
  .createPipelineLayout,
  .createQueryPool,
  .createRenderPass,
  .createSemaphore,
  .createShaderModule,
  // .createSwapchainKHR,
  // .destroyAccelerationStructureKHR ,
  .destroyBuffer,
  .destroyCommandPool,
  .destroyDescriptorPool ,
  .destroyDescriptorSetLayout ,
  .destroyDevice,
  .destroyFence,
  .destroyFramebuffer,
  .destroyImage,
  .destroyImageView,
  .destroyPipelineLayout,
  .destroyPipeline,
  .destroyQueryPool,
  .destroyRenderPass,
  .destroySampler ,
  .destroySemaphore,
  .destroyShaderModule,
  // .destroySwapchainKHR,
  .deviceWaitIdle,
  .endCommandBuffer,
  .freeCommandBuffers,
  .freeDescriptorSets ,
  .freeMemory,
  // // .getAccelerationStructureBuildSizesKHR,
  .getBufferDeviceAddress,
  .getBufferMemoryRequirements2 ,
  .getBufferMemoryRequirements,
  .getDeviceQueue,
  // .getSwapchainImagesKHR,
  .mapMemory,
  // .queuePresentKHR,
  .queueSubmit,
  .queueWaitIdle,
  .resetFences,
  .resetQueryPool,
  // .setDebugUtilsObjectNameEXT ,
  .unmapMemory,
  .updateDescriptorSets,
  .waitForFences,
});
